version: '3'
services:
  app:
    image: $APP_IMG
    volumes:
      - ../app_data:/data
    depends_on:
      - "mysql"
      - "redis_cluster"
    stdin_open: true
    tty: true
    container_name: "$PROJECT_NAME"
    env_file:
      - ../conf/app.env
    ports:
      - 8004:8004
    entrypoint: ["/bin/bash", "-c",
      "/bin/bash $${PROJECT_PATH}/docker/wait_deps.sh /bin/sh $${PROJECT_PATH}/docker/start.sh"]

  mysql:
    image: xianzixiang/mysql
    volumes:
      - ../mysql/conf:/etc/mysql/conf.d
      - ../mysql/logs:/logs
      - ../mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3309:3306
    container_name: "$MYSQL_HOST"
    env_file:
      - ../conf/app.env

  redis_cluster:
    image: xianzixiang/redis-cluster:3.2.12
    container_name: "$REDIS_NAME"
    ports:
      - 7000:7000