language: python
python:
- "3.5"
services:
- docker
env:
- APP_VERSION=1.0
jobs:
  include:
  - stage: build docker image
    script:
    - chmod +x ./build/buildApp.sh && ./build/buildApp.sh $APP_VERSION
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - chmod +x ./build/pushApp.sh && ./build/pushApp.sh $APP_VERSION
  - stage: deploy server
    script:
    - chmod +x ./build/deploy.sh && ./build/deploy.sh "$DOCKER_USERNAME"

branches:
  only:
  - master