language: python
python:
- "3.5"
services:
- docker
env:
- APP_VERSION=1.0
script:
- chmod +x buildApp.sh && buildApp.sh $APP_VERSION
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push xianzixiang/`echo -n $PROJECT_NAME | awk '{print tolower($0)}'`:$V

branches:
  only:
  - dev