language: python
python:
- "3.5"
services:
- docker
env:
- APP_VERSION=latest
jobs:
  include:
  - stage: build docker image
    script:
    - chmod +x ./build/buildApp.sh && ./build/buildApp.sh $APP_VERSION
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - chmod +x ./build/pushApp.sh && ./build/pushApp.sh $APP_VERSION
#  - stage: check whether server is alive
#    script:
#    - chmod +x ./docker/livenessProbe.sh && ./docker/livenessProbe.sh

deploy:
  skip_cleanup: true
  provider: script
  script:
  - curl http://faithio.cn:9000/hooks/deploy-base


branches:
  only:
  - master

git:
  depth: 5