version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PROJECT_NAME: "$PROJECT_NAME"
        PROJECT_PATH: "$PROJECT_PATH"
    volumes:
      - ./app_data:/data
    depends_on:
      - "redis_cluster"
    stdin_open: true
    tty: true
    container_name: "$PROJECT_NAME"
    env_file:
      - conf/app.env
    ports:
      - 8004:8004
    entrypoint: ["/bin/bash", "-c",
      "/bin/bash $${PROJECT_PATH}/docker/wait_deps.sh /bin/sh $${PROJECT_PATH}/docker/start.sh"]


  redis_cluster:
    image: xianzixiang/redis-cluster:3.2.12
    hostname: redis-server
#    extra_hosts:
#      redis-server: 10.13.X.X
    container_name: "$REDIS_NAME"
    environment:
      IP: '0.0.0.0'
      SENTINEL: 'true'
      STANDALONE: 'false'
    ports:
      - 7000:7000

networks:
  default:
    external:
      name: mysql-network