version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql.Dockerfile
    volumes:
    - ./mysql/conf:/etc/mysql/conf.d
    - ./mysql/logs:/logs
    - ./mysql/data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=$MYSQL_PWD
    ports:
    - 3309:3306
    container_name: "$MYSQL_HOST"

networks:
  default:
    external:
      name: mysql-network